name: example
description: Example project for arculus
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  copy_with_extension: 1.4.0
  arculus:
    path: ../
  arculus_auth_widgets: 0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.10.9
  copy_with_extension_gen: 1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/
